name: Cypress Test Execution
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3
 
     - name: Node version
       uses: actions/setup-node@v3
       with:
         node-version: '14'
     - run: npm install

     - name: Run TestCases
       uses: cypress-io/github-action@v6
       with:
         command: npm run test
